version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

  swift-order-spring:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - kafka
      - postgres
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      SWIFT_ORDER_REPO_TYPE: postgres
      SWIFT_ORDER_REPO_CONFIG_HOST: postgres
      SWIFT_ORDER_REPO_CONFIG_PORT: 5432
      SWIFT_ORDER_REPO_CONFIG_USER: swiftorder
      SWIFT_ORDER_REPO_CONFIG_PASSWORD: swiftorder
      SWIFT_ORDER_REPO_CONFIG_DATABASE: swiftorder

  swift-order-ui:
    build:
      context: ..
      dockerfile: docker/Dockerfile.ui
    ports:
      - "8081:8081"
    depends_on:
      - swift-order-spring
      - kafka
    environment:
      BACKEND_URL: http://swift-order-spring:8080
      KAFKA_BOOTSTRAP: kafka:29092

  postgres:
    image: postgres:17
    platform: linux/amd64
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: swiftorder
      POSTGRES_PASSWORD: swiftorder
      POSTGRES_DB: swiftorder

  kafka-ui:
    image: provectuslabs/kafka-ui:v0.7.2
    ports:
      - "8082:8080"
    depends_on:
      - kafka
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
